version: "3.8"

services:
  training-nodemailer-app:
    container_name: training-nodemailer-app
    image: training-nodemailer-app
    restart: always
    environment:
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      API_PORT=: ${API_PORT}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_PORT: ${API_PORT}
#    ports:
#      - ${API_PORT}:${API_PORT}
    networks:
      - training-nodemailer

networks:
  training-nodemailer:
    name: training-nodemailer
